### ISSUE TITLE
Contenttyp Künstler*in

### ISSUE THREAD

**Issue by steffirogoll** [immergutrocken/cms#20]
AK

- [x] Titel (l11n)

- [x] Banner

- [ ] Contentbereich
     [ ] Text (l11n)
     [ ] Bilder
     [ ] Videos
     [ ] Gallerien
     [ ] Ausrichtung
     [ ] Links (Bildlinks) (l11n)
     [ ] CTA Buttons (l11n)
     [ ] Liste
     [ ] Gifs

- [ ] Slug

- [ ] Social Media Links
     [ ] Titel
     [ ] Link
     [ ] Icon

- [ ] Untertitel (l11n)

- [ ] Autoreninfo-Feld

- [ ] Kategorie 
     [ ] Musik
     [ ] Lesung

- [ ] Tags

**Comment by hagenstrahl** [comment]
@steffirogoll @lottechar14 Welche Soziale Medien wollen wir denn erstmal unterstützen? Oder wollt ihr das selbst bestimmen können? Dann müssen wir nochmal einen neuen Content Type erstellen :)

**Comment by steffirogoll** [comment]
@hagenstrahl kann natürlich sein, dass sich das in 1-2 Jahre nochmal zeitgeistmäßig ändern wird aber wir gehen jetzt mit Homepage des Artists, Instagram, Spotifyprofil und Facebook ins Rennen. Kann dann ja auch leer bleiben wenn das bei dem/der ein oder anderen nicht existiert, korrekt?

**Comment by hagenstrahl** [comment]
Ok die bastel ich rein. Youtube und Twitter auch?
Genau, man kann die beliebig hinzufügen und auch die Reihenfolge ändern:
![image](https://user-images.githubusercontent.com/34143718/103137319-3c0fbd00-46c8-11eb-9c49-dbd30a32363f.png)
Oder sollen das richtig festgelegte Felder sein, die gleich alle untereinander stehen?

**Comment by steffirogoll** [comment]
@hagenstrahl ok, dann lass uns gleich die Megaauswahl schaffen und die dann eben benutzen in der Contentpflege sobald wir wollen. Dementsprechend der Blumenstrauß: Facebook, Twitter, Instagram, YouTube, Vimeo, TikTok, Homepage, Spotify
